name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master


jobs:
  job_build:
    name: Compilation
    strategy:
      matrix:
        include:
          - model: nanos
            SDK: "$NANOS_SDK"
          - model: nanox
            SDK: "$NANOX_SDK"
          - model: nanosp
            SDK: "$NANOSP_SDK"
          - model: stax
            SDK: "$STAX_SDK"

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: |
          make BOLOS_SDK=${{ matrix.SDK }} && mv bin/ bitcoin-bin/
          make clean
          make COIN=bitcoin_testnet_legacy BOLOS_SDK=${{ matrix.SDK }} && mv bin/ bitcoin-testnet-bin/

      - name: Upload Bitcoin app binary
        uses: actions/upload-artifact@v2
        with:
          name: bitcoin-app-${{ matrix.model }}
          path: bitcoin-bin

      - name: Upload Bitcoin Testnet app binary
        uses: actions/upload-artifact@v2
        with:
          name: bitcoin-testnet-app-${{ matrix.model }}
          path: bitcoin-testnet-bin

  job_test:
    name: Tests
    strategy:
      matrix:
        include:
          - model: nanos
          - model: nanox
          - model: nanosp
          - model: stax

    needs: job_build
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/speculos:latest
      ports:
        - 1234:1234
        - 9999:9999
        - 40000:40000
        - 41000:41000
        - 42000:42000
        - 43000:43000
      options: --entrypoint /bin/bash

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Download Bitcoin app binary
        uses: actions/download-artifact@v2
        with:
          name: bitcoin-app-${{matrix.model}}
          path: tests/bitcoin-bin

      - name: Download Bitcoin Testnet app binary
        uses: actions/download-artifact@v2
        with:
          name: bitcoin-testnet-app-${{ matrix.model }}
          path: tests/bitcoin-testnet-bin

      - name: Run tests
        run: |
          cd tests && pip install -r requirements.txt && SPECULOS=/speculos/speculos.py pytest --model=${{ matrix.model }}

